# Generated by Django 3.2.8 on 2021-10-26 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('nickname', models.CharField(default='', max_length=20, unique=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AgeNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('ages', models.CharField(max_length=10)),
                ('nutrient', models.CharField(max_length=30)),
                ('upper', models.FloatField()),
                ('lower', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GoodForLifeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GoodForOrgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upper', models.FloatField(blank=True, null=True)),
                ('lower', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('tmp_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('nutrient', models.ForeignKey(db_column='nutrient', on_delete=django.db.models.deletion.CASCADE, to='api.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('company', models.CharField(max_length=50)),
                ('exp_date', models.CharField(max_length=50)),
                ('dispos', models.CharField(max_length=50)),
                ('sug_use', models.CharField(max_length=100)),
                ('warning', models.CharField(max_length=500)),
                ('pri_func', models.CharField(max_length=500)),
                ('raw_material', models.CharField(max_length=500)),
                ('tmp_id', models.CharField(max_length=30)),
                ('nuntrient', models.ManyToManyField(through='api.NutritionFact', to='api.Nutrient')),
                ('user_review', models.ManyToManyField(through='api.Review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='supplement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplement'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_nicname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=20)),
                ('nutrient', models.ManyToManyField(through='api.GoodForOrgan', to='api.Nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='supplement',
            field=models.ForeignKey(db_column='supplement', on_delete=django.db.models.deletion.CASCADE, to='api.supplement'),
        ),
        migrations.CreateModel(
            name='LifeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_style', models.CharField(max_length=50)),
                ('nutrient', models.ManyToManyField(through='api.GoodForLifeStyle', to='api.Nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='goodfororgan',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nutrient'),
        ),
        migrations.AddField(
            model_name='goodfororgan',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organ'),
        ),
        migrations.AddField(
            model_name='goodforlifestyle',
            name='life_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lifestyle'),
        ),
        migrations.AddField(
            model_name='goodforlifestyle',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nutrient'),
        ),
        migrations.CreateModel(
            name='GoodForBodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bodytype')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='bodytype',
            name='nutrient',
            field=models.ManyToManyField(through='api.GoodForBodyType', to='api.Nutrient'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.age'),
        ),
        migrations.AddField(
            model_name='user',
            name='body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bodytype'),
        ),
    ]
