# Generated by Django 3.2.8 on 2021-11-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='review_num',
            field=models.IntegerField(default=0),
        ),
    ]
