# Generated by Django 3.2.8 on 2021-10-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='upper',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
