# Generated by Django 3.2.8 on 2021-10-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodytype',
            name='nutrient',
        ),
        migrations.RemoveField(
            model_name='lifestyle',
            name='nutrient',
        ),
        migrations.RemoveField(
            model_name='organ',
            name='nutrient',
        ),
        migrations.AlterField(
            model_name='goodfororgan',
            name='nutrient',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goodfororgan',
            name='organ',
            field=models.CharField(max_length=10),
        ),
    ]
