# Generated by Django 3.2.8 on 2021-10-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211027_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodforbodytype',
            name='body_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='goodforbodytype',
            name='nutrient',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goodforlifestyle',
            name='life_style',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goodforlifestyle',
            name='nutrient',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goodfororgan',
            name='organ',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='life_style',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='organ',
            name='organ',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
