# Generated by Django 3.2.8 on 2021-10-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211022_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
