# Generated by Django 3.2.8 on 2021-11-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_supplement_review_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='supplement',
            new_name='supplement_pk',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_nickname',
            new_name='user_pk',
        ),
    ]
