# Generated by Django 3.2.8 on 2021-10-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211029_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_nicname',
            new_name='user_nickname',
        ),
    ]
