# Generated by Django 3.2.8 on 2021-11-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211105_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='age_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.age'),
        ),
        migrations.AddField(
            model_name='review',
            name='bodytype_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bodytype'),
        ),
        migrations.AddField(
            model_name='review',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
