# Generated by Django 3.2.8 on 2021-11-10 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211107_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='taking_num',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TakingSupplements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplement')),
                ('user_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
