# Generated by Django 3.2.8 on 2021-10-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211025_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionfact',
            name='nutrient',
            field=models.ForeignKey(db_column='nutrient', on_delete=django.db.models.deletion.CASCADE, to='api.nutrient'),
        ),
        migrations.AlterField(
            model_name='nutritionfact',
            name='supplement',
            field=models.ForeignKey(db_column='supplement', on_delete=django.db.models.deletion.CASCADE, to='api.supplement'),
        ),
    ]
